config/routes.rb
Rails.application.routes.draw do

  resources :tasks do
    resources :comments
    resources :subtasks
  end

  resources :subtasks do
    resources :subcomments
  end
  
  devise_for :users
  root to: "tasks#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
end

app/models/subcomment.rb
class Subcomment < ApplicationRecord
  belongs_to :subtask
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  belongs_to :task
  has_many :subcomments, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :subtasks, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @task = Task.find(params[:task_id])
    @comment = @task.comments.create(comment_params)
    redirect_to task_path(@task)
  end
 
  def destroy
    @task = Task.find(params[:task_id])
    @comment = @task.comments.find(params[:id])
    @comment.destroy
    redirect_to task_path(@task)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:comment_text)
    end
end

app/controllers/subcomments_controller.rb
class SubcommentsController < ApplicationController

  def create
    @subtask = Subtask.find(params[:subtask_id])
    @subcomment = @subtask.subcomments.create(subcomment_params)
    redirect_to subtask_path(@subtask)
  end
 
  def destroy
    @subtask = Subtask.find(params[:subtask_id])
    @subcomment = @subtask.subcomments.find(params[:id])
    @subcomment.destroy
    redirect_to subtask_path(@subtask)
  end
 
  private
    def subcomment_params
      params.require(:subcomment).permit(:subcomment_text)
    end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  before_action :set_subtask, only: [:show, :edit, :update, :destroy]

  # GET /subtasks
  # GET /subtasks.json
  def index
    @subtasks = Subtask.all
  end

  # GET /subtasks/1
  # GET /subtasks/1.json
  def show
  end

  # GET /subtasks/new
  def new
    @subtask = Subtask.new
  end

  # GET /subtasks/1/edit
  def edit
  end

  # POST /subtasks
  # POST /subtasks.json
  def create
    @subtask = Subtask.new(subtask_params)

    respond_to do |format|
      if @subtask.save
        format.html { redirect_to @subtask, notice: 'Subtask was successfully created.' }
        format.json { render :show, status: :created, location: @subtask }
      else
        format.html { render :new }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subtasks/1
  # PATCH/PUT /subtasks/1.json
  def update
    respond_to do |format|
      if @subtask.update(subtask_params)
        format.html { redirect_to @subtask, notice: 'Subtask was successfully updated.' }
        format.json { render :show, status: :ok, location: @subtask }
      else
        format.html { render :edit }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subtasks/1
  # DELETE /subtasks/1.json
  def destroy
    @subtask.destroy
    respond_to do |format|
      format.html { redirect_to subtasks_url, notice: 'Subtask was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subtask
      @subtask = Subtask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subtask_params
      params.require(:subtask).permit(:subtask_text, :subtask_release_date, :subtask_status, :subtask_priority, :task_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task_text, :task_release_date, :task_status, :task_priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subcomments_helper.rb
module SubcommentsHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>    
  <body>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>

    <%= yield %>
  </body>
</html>

app/views/subtasks/_form.html.erb
<%= form_with(model: subtask, local: true) do |form| %>
  <% if subtask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subtask.errors.count, "error") %> prohibited this subtask from being saved:</h2>

      <ul>
      <% subtask.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subtask_text %>
    <%= form.text_field :subtask_text, id: :subtask_subtask_text %>
  </div>

  <div class="field">
    <%= form.label :subtask_release_date %>
    <%= form.datetime_select :subtask_release_date, id: :subtask_subtask_release_date %>
  </div>

  <div class="field">
    <%= form.label :subtask_status %>
    <%= form.text_field :subtask_status, id: :subtask_subtask_status %>
  </div>

  <div class="field">
    <%= form.label :subtask_priority %>
    <%= form.text_field :subtask_priority, id: :subtask_subtask_priority %>
  </div>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.text_field :task_id, id: :subtask_task_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subtasks/edit.html.erb
<h1>Editing Subtask</h1>

<%= render 'form', subtask: @subtask %>

<%= link_to 'Show', @subtask %> |
<%= link_to 'Back', subtasks_path %>

app/views/subtasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subtasks</h1>

<table>
  <thead>
    <tr>
      <th>Subtask text</th>
      <th>Subtask release date</th>
      <th>Subtask status</th>
      <th>Subtask priority</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subtasks.each do |subtask| %>
      <tr>
        <td><%= subtask.subtask_text %></td>
        <td><%= subtask.subtask_release_date %></td>
        <td><%= subtask.subtask_status %></td>
        <td><%= subtask.subtask_priority %></td>
        <td><%= subtask.task_id %></td>
        <td><%= link_to 'Show', subtask %></td>
        <td><%= link_to 'Edit', edit_subtask_path(subtask) %></td>
        <td><%= link_to 'Destroy', subtask, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subtask', new_subtask_path %>

app/views/subtasks/new.html.erb
<h1>New Subtask</h1>

<%= render 'form', subtask: @subtask %>

<%= link_to 'Back', subtasks_path %>

app/views/subtasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subtask text:</strong>
  <%= @subtask.subtask_text %>
</p>

<p>
  <strong>Subtask release date:</strong>
  <%= @subtask.subtask_release_date %>
</p>

<p>
  <strong>Subtask status:</strong>
  <%= @subtask.subtask_status %>
</p>

<p>
  <strong>Subtask priority:</strong>
  <%= @subtask.subtask_priority %>
</p>

<h2>Subcomments</h2>
<% @subtask.subcomments.each do |subcomment| %>
  <p>
    <strong>subcomment:</strong>
    <%= subcomment.subcomment_text %>
  </p>

  <p>
    <%= link_to 'Destroy Subcomment', [subcomment.subtask, subcomment],
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>
 
<h2>Add a subcomment:</h2>
<%= form_with(model: [ @subtask, @subtask.subcomments.build ]) do |form| %>
  <p>
    <%= form.label :subcomment_text %><br>
    <%= form.text_area :subcomment_text %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Edit', edit_subtask_path(@subtask) %> |
<%= link_to 'Back', subtasks_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_text %>
    <%= form.text_field :task_text, id: :task_task_text %>
  </div>

  <div class="field">
    <%= form.label :task_release_date %>
    <%= form.datetime_select :task_release_date, id: :task_task_release_date %>
  </div>

  <div class="field">
    <%= form.label :task_status %>
    <%= form.text_field :task_status, id: :task_task_status %>
  </div>

  <div class="field">
    <%= form.label :task_priority %>
    <%= form.text_field :task_priority, id: :task_task_priority %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Task text</th>
      <th>Task release date</th>
      <th>Task status</th>
      <th>Task priority</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.task_text %></td>
        <td><%= task.task_release_date %></td>
        <td><%= task.task_status %></td>
        <td><%= task.task_priority %></td>
        <td><%= task.user.email %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task text:</strong>
  <%= @task.task_text %>
</p>

<p>
  <strong>Task release date:</strong>
  <%= @task.task_release_date %>
</p>

<p>
  <strong>Task status:</strong>
  <%= @task.task_status %>
</p>

<p>
  <strong>Task priority:</strong>
  <%= @task.task_priority %>
</p>

<h2>Comments</h2>
<% @task.comments.each do |comment| %>
  <p>
    <strong>Comment:</strong>
    <%= comment.comment_text %>
  </p>

  <p>
    <%= link_to 'Destroy Comment', [comment.task, comment],
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>
 
<h2>Add a comment:</h2>
<%= form_with(model: [ @task, @task.comments.build ]) do |form| %>
  <p>
    <%= form.label :comment_text %><br>
    <%= form.text_area :comment_text %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>


<h2>Subtasks</h2>
<% @task.subtasks.each do |subtask| %>
  <td><%= link_to 'Show', subtask %></td>
  <td><%= link_to 'Destroy', subtask, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

<h2>Add a subtask:</h2>
<%= link_to 'New Subtask', new_subtask_path %>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>